# Generated by Django 3.0.5 on 2020-04-30 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='mention',
            field=models.ManyToManyField(blank=True, related_name='mention', to=settings.AUTH_USER_MODEL),
        ),
    ]
