# Generated by Django 3.0.5 on 2020-04-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200429_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followed',
            field=models.BooleanField(default=False),
        ),
    ]
