# Generated by Django 3.0.6 on 2020-05-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200506_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('not specified', 'Prefer not specified')], default='not specified', max_length=40, null=True),
        ),
    ]
