# Generated by Django 3.0.6 on 2020-05-31 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followed',
        ),
    ]
