# Generated by Django 3.0.6 on 2020-06-07 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200601_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='followrelationship',
            name='followed',
            field=models.ManyToManyField(related_name='followed', to=settings.AUTH_USER_MODEL),
        ),
    ]
