# Generated by Django 3.0.6 on 2020-06-08 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_followrelationship_followed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowRelationship',
        ),
    ]
