# Generated by Django 3.0.5 on 2020-04-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_auto_20200430_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggedusers',
            name='photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='tagged',
            field=models.ManyToManyField(blank=True, to='photos.TaggedUsers'),
        ),
    ]
