# Generated by Django 3.0.5 on 2020-04-30 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0008_auto_20200430_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='tagged',
            field=models.ManyToManyField(blank=True, related_name='tagged', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TaggedUsers',
        ),
    ]
