# Generated by Django 3.0.6 on 2020-05-06 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_auto_20200502_1104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-created']},
        ),
    ]
