# Generated by Django 3.0.6 on 2020-06-07 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0011_auto_20200506_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='photo',
            name='updated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
