# Generated by Django 3.0.6 on 2020-06-07 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0012_auto_20200607_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='photo',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
