# Generated by Django 3.0.6 on 2020-06-07 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0013_auto_20200607_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='is_liked',
        ),
    ]
