# Generated by Django 3.0.6 on 2020-06-07 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0015_auto_20200607_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagged',
            name='photo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='photos.Photo'),
        ),
    ]
